"""Backpressure demo (#3): fast producer, slow consumer, bounded queue.

Proves the OOM-safety claim: when the producer emits items faster than
the consumer can drain them, ``stream``'s bounded queue holds peak heap
to ``queue_size`` items regardless of how many items the producer
would emit. Without backpressure, a naive `asyncio.Queue` with no
``maxsize`` (or a plain list) grows linearly with producer rate.

Numbers are real and reproducible:

    python scripts/bench_backpressure.py --n 5000 --queue-size 8 \\
        --consumer-ms 1 --concurrency 2

Writes ``docs/backpressure.md`` and ``docs/backpressure.json`` with the
measured peak-heap and pause-time numbers. The bench is dep-free
(``tracemalloc`` and ``asyncio`` are stdlib) so D-002 holds.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import sys
import time
import tracemalloc
from collections.abc import AsyncIterator
from dataclasses import asdict, dataclass
from pathlib import Path

# Allow ``python scripts/bench_backpressure.py`` from a fresh checkout.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from async_pipelines import StreamMetrics, stream  # noqa: E402


@dataclass
class BackpressureResult:
    """One run's measured numbers."""

    n: int
    queue_size: int
    consumer_ms: float
    concurrency: int
    duration_s: float
    peak_heap_kb: float
    metrics: dict[str, float | int]


async def _fast_producer(n: int) -> AsyncIterator[int]:
    """A producer with zero per-item latency — the worst case for a
    slow consumer because every item is ready immediately.
    """
    for i in range(n):
        yield i


def _make_slow_consumer(consumer_ms: float):
    async def consume(x: int) -> int:
        await asyncio.sleep(consumer_ms / 1000.0)
        return x

    return consume


async def run_one(
    *, n: int, queue_size: int, consumer_ms: float, concurrency: int
) -> BackpressureResult:
    """Run a single (n, queue_size, consumer_ms, concurrency) cell and
    return the measured numbers.
    """
    m = StreamMetrics()
    consume = _make_slow_consumer(consumer_ms)

    tracemalloc.start()
    start = time.perf_counter()
    await stream(
        _fast_producer(n),
        consume,
        concurrency=concurrency,
        queue_size=queue_size,
        metrics=m,
    )
    duration_s = time.perf_counter() - start
    _current, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    return BackpressureResult(
        n=n,
        queue_size=queue_size,
        consumer_ms=consumer_ms,
        concurrency=concurrency,
        duration_s=duration_s,
        peak_heap_kb=peak / 1024.0,
        metrics=asdict(m),
    )


def _render_markdown(results: list[BackpressureResult]) -> str:
    lines: list[str] = []
    lines.append("# Backpressure demo (#3)\n")
    lines.append(
        "Generated by `scripts/bench_backpressure.py`. The producer emits "
        "items with zero per-item latency; the consumer sleeps "
        "`--consumer-ms` per item. `stream`'s bounded `asyncio.Queue` "
        "applies backpressure when the consumer can't keep up.\n"
    )
    lines.append("## Measured\n")
    lines.append(
        "| n | queue_size | consumer_ms | concurrency | duration_s | "
        "peak_heap_kb | producer_pauses | max_queue_depth | pause_seconds |\n"
        "|---:|---:|---:|---:|---:|---:|---:|---:|---:|"
    )
    for r in results:
        m = r.metrics
        lines.append(
            f"| {r.n} | {r.queue_size} | {r.consumer_ms} | {r.concurrency} | "
            f"{r.duration_s:.3f} | {r.peak_heap_kb:.1f} | "
            f"{m['producer_pauses']} | {m['max_queue_depth']} | "
            f"{m['producer_pause_seconds']:.3f} |"
        )
    lines.append("")
    lines.append("## OOM-safety claim\n")
    lines.append(
        "`max_queue_depth` is bounded by `queue_size` in every row above "
        "regardless of `n`. That's the invariant that makes `stream` safe "
        "to point at an unbounded source: peak in-memory items are O("
        "queue_size), not O(producer_rate × time)."
    )
    lines.append("")
    return "\n".join(lines)


async def main_async(args: argparse.Namespace) -> int:
    if args.n <= 0 or args.queue_size <= 0 or args.concurrency <= 0:
        print("n, queue-size, and concurrency must all be positive", file=sys.stderr)
        return 2
    if args.consumer_ms < 0:
        print("consumer-ms must be non-negative", file=sys.stderr)
        return 2

    cells: list[tuple[int, int, float, int]] = [
        (args.n, args.queue_size, args.consumer_ms, args.concurrency),
    ]
    # Add a same-n / 4x-queue cell to make the bound visible in the table.
    if args.compare:
        cells.append((args.n, args.queue_size * 4, args.consumer_ms, args.concurrency))

    results: list[BackpressureResult] = []
    for n, qs, cms, c in cells:
        r = await run_one(n=n, queue_size=qs, consumer_ms=cms, concurrency=c)
        results.append(r)
        print(
            f"n={r.n} qs={r.queue_size} cms={r.consumer_ms} c={r.concurrency} "
            f"→ duration={r.duration_s:.3f}s peak={r.peak_heap_kb:.1f}kb "
            f"pauses={r.metrics['producer_pauses']} "
            f"max_depth={r.metrics['max_queue_depth']}"
        )

    if args.out_md:
        Path(args.out_md).parent.mkdir(parents=True, exist_ok=True)
        Path(args.out_md).write_text(_render_markdown(results))
        print(f"wrote {args.out_md}")
    if args.out_json:
        Path(args.out_json).parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "results": [asdict(r) for r in results],
            "host": sys.platform,
            "python": sys.version.split()[0],
        }
        Path(args.out_json).write_text(json.dumps(payload, indent=2))
        print(f"wrote {args.out_json}")

    return 0


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Bounded-queue backpressure demo (#3).")
    p.add_argument("--n", type=int, default=5000, help="items to push through the pipeline")
    p.add_argument("--queue-size", type=int, default=8, help="bounded queue size")
    p.add_argument("--consumer-ms", type=float, default=1.0, help="per-item consumer sleep")
    p.add_argument("--concurrency", type=int, default=2, help="consumer fan-out")
    p.add_argument(
        "--compare",
        action="store_true",
        help="also run with 4x queue_size to show the heap bound moves",
    )
    p.add_argument("--out-md", default="docs/backpressure.md", help="markdown report")
    p.add_argument("--out-json", default="docs/backpressure.json", help="json report")
    return p


def main() -> int:
    args = _build_parser().parse_args()
    return asyncio.run(main_async(args))


if __name__ == "__main__":
    raise SystemExit(main())
